/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTestRouteImport } from './routes/dashboard/test'
import { Route as DashboardInfluencersRouteImport } from './routes/dashboard.influencers'
import { Route as DashboardCampaignsRouteImport } from './routes/dashboard.campaigns'
import { Route as DashboardAiLabRouteImport } from './routes/dashboard/ai-lab'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTestRoute = DashboardTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInfluencersRoute = DashboardInfluencersRouteImport.update({
  id: '/influencers',
  path: '/influencers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCampaignsRoute = DashboardCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiLabRoute = DashboardAiLabRouteImport.update({
  id: '/ai-lab',
  path: '/ai-lab',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/pricing': typeof PricingRoute
  '/dashboard/ai-lab': typeof DashboardAiLabRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/influencers': typeof DashboardInfluencersRoute
  '/dashboard/test': typeof DashboardTestRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/dashboard/ai-lab': typeof DashboardAiLabRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/influencers': typeof DashboardInfluencersRoute
  '/dashboard/test': typeof DashboardTestRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/pricing': typeof PricingRoute
  '/dashboard/ai-lab': typeof DashboardAiLabRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/influencers': typeof DashboardInfluencersRoute
  '/dashboard/test': typeof DashboardTestRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/pricing'
    | '/dashboard/ai-lab'
    | '/dashboard/campaigns'
    | '/dashboard/influencers'
    | '/dashboard/test'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/dashboard/ai-lab'
    | '/dashboard/campaigns'
    | '/dashboard/influencers'
    | '/dashboard/test'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/pricing'
    | '/dashboard/ai-lab'
    | '/dashboard/campaigns'
    | '/dashboard/influencers'
    | '/dashboard/test'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/test': {
      id: '/dashboard/test'
      path: '/test'
      fullPath: '/dashboard/test'
      preLoaderRoute: typeof DashboardTestRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/influencers': {
      id: '/dashboard/influencers'
      path: '/influencers'
      fullPath: '/dashboard/influencers'
      preLoaderRoute: typeof DashboardInfluencersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campaigns': {
      id: '/dashboard/campaigns'
      path: '/campaigns'
      fullPath: '/dashboard/campaigns'
      preLoaderRoute: typeof DashboardCampaignsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-lab': {
      id: '/dashboard/ai-lab'
      path: '/ai-lab'
      fullPath: '/dashboard/ai-lab'
      preLoaderRoute: typeof DashboardAiLabRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAiLabRoute: typeof DashboardAiLabRoute
  DashboardCampaignsRoute: typeof DashboardCampaignsRoute
  DashboardInfluencersRoute: typeof DashboardInfluencersRoute
  DashboardTestRoute: typeof DashboardTestRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiLabRoute: DashboardAiLabRoute,
  DashboardCampaignsRoute: DashboardCampaignsRoute,
  DashboardInfluencersRoute: DashboardInfluencersRoute,
  DashboardTestRoute: DashboardTestRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
